name: Repository Events
on: [push, pull_request, issues]

jobs:

    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: github_sha
              run: |
                echo $GITHUB_SHA
                eeho $GITHUB_REF
            - uses: actions/checkout@v3
        