name: Workflow Commands
on : [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-22.04
        steps:
            - name: Setting and error Message
              run: echo "::error::Missing semicolon"

            - name: error
              run: echo "::error title:Error tittle, file=app.js,line=2, endLine=3, col=5, endColumn=7 ::Missing Semicolon"

            - name: debug
              run: echo "::debug title:Debug tittle, file=app.js, line=2, endLine=3, col=5, endColumn=7 ::Missing Semicolon"
        
            - name: warning
              run: echo "::warning title:Warning tittle, file=app.js,line=2, endLine=3, col=5, endColumn=7 ::Missing Semicolon"

            - name: notice
              run: echo "::notice title:Notice tittle, file=app.js,line=2, endLine=3, col=5, endColumn=7 ::Missing Semicolon"
            
            - name: group
              run: |
                echo "::group:: My group title"
                echo "Inside the group"
                echo "::endgroup::"

            - name: masking a value
              run: echo "::add-mask::Secret String"
            
            - name: secret a value
              run: echo "secret string"
