name: Workflow Commands
on : [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-22.04
        steps:
            - name: Setting and error Message
              run: echo "::error::Missing semicolon"
